#!/bin/bash
# Runs automatically when a Codespace is created.
# Generates .env.local from Codespace secrets + sets NEXTAUTH_URL dynamically.

set -e

ENV_FILE=".env.local"

echo "# Auto-generated by .devcontainer/setup.sh — do not edit manually" > "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── Database ──────────────────────────────────────────────────────────────────
echo "DATABASE_URL=\"${DATABASE_URL}\"" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── Auth ──────────────────────────────────────────────────────────────────────
# Build NEXTAUTH_URL from Codespace env vars automatically
NEXTAUTH_URL="https://${CODESPACE_NAME}-3000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
echo "NEXTAUTH_SECRET=\"${NEXTAUTH_SECRET}\"" >> "$ENV_FILE"
echo "NEXTAUTH_URL=\"${NEXTAUTH_URL}\"" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── Supabase ──────────────────────────────────────────────────────────────────
echo "NEXT_PUBLIC_SUPABASE_URL=\"${NEXT_PUBLIC_SUPABASE_URL}\"" >> "$ENV_FILE"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=\"${NEXT_PUBLIC_SUPABASE_ANON_KEY}\"" >> "$ENV_FILE"
echo "SUPABASE_SERVICE_ROLE_KEY=\"${SUPABASE_SERVICE_ROLE_KEY}\"" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── Stripe ────────────────────────────────────────────────────────────────────
echo "STRIPE_SECRET_KEY=\"${STRIPE_SECRET_KEY}\"" >> "$ENV_FILE"
echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=\"${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}\"" >> "$ENV_FILE"
echo "STRIPE_WEBHOOK_SECRET=\"${STRIPE_WEBHOOK_SECRET}\"" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── Email — Resend ────────────────────────────────────────────────────────────
echo "RESEND_API_KEY=\"${RESEND_API_KEY}\"" >> "$ENV_FILE"
echo "EMAIL_FROM=\"${EMAIL_FROM}\"" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── AI ────────────────────────────────────────────────────────────────────────
echo "ANTHROPIC_API_KEY=\"${ANTHROPIC_API_KEY}\"" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── Rate Limiting — Upstash ───────────────────────────────────────────────────
echo "UPSTASH_REDIS_REST_URL=\"${UPSTASH_REDIS_REST_URL}\"" >> "$ENV_FILE"
echo "UPSTASH_REDIS_REST_TOKEN=\"${UPSTASH_REDIS_REST_TOKEN}\"" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── Error Monitoring — Sentry ─────────────────────────────────────────────────
echo "NEXT_PUBLIC_SENTRY_DSN=\"${NEXT_PUBLIC_SENTRY_DSN}\"" >> "$ENV_FILE"
echo "SENTRY_ORG=\"${SENTRY_ORG}\"" >> "$ENV_FILE"
echo "SENTRY_PROJECT=\"${SENTRY_PROJECT}\"" >> "$ENV_FILE"
echo "SENTRY_AUTH_TOKEN=\"${SENTRY_AUTH_TOKEN}\"" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── Platform ──────────────────────────────────────────────────────────────────
echo "NEXT_PUBLIC_PLATFORM_NAME=\"${NEXT_PUBLIC_PLATFORM_NAME}\"" >> "$ENV_FILE"
echo "NEXT_PUBLIC_PLATFORM_TAGLINE=\"${NEXT_PUBLIC_PLATFORM_TAGLINE}\"" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── Coming Soon ───────────────────────────────────────────────────────────────
echo "COMING_SOON=${COMING_SOON:-false}" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# ── Infrastructure ────────────────────────────────────────────────────────────
# GITHUB_TOKEN is automatically provided by Codespaces
echo "GITHUB_TOKEN=\"${GITHUB_TOKEN}\"" >> "$ENV_FILE"
echo "GITHUB_REPO=\"AI-VisionariesStudio/The-Wellness-Collection\"" >> "$ENV_FILE"
echo "VERCEL_TOKEN=\"${VERCEL_TOKEN}\"" >> "$ENV_FILE"
echo "VERCEL_PROJECT_ID=\"${VERCEL_PROJECT_ID}\"" >> "$ENV_FILE"
echo "BETTERSTACK_API_KEY=\"${BETTERSTACK_API_KEY}\"" >> "$ENV_FILE"
echo "VIMEO_ACCESS_TOKEN=\"${VIMEO_ACCESS_TOKEN}\"" >> "$ENV_FILE"

echo ""
echo "✓ .env.local written (NEXTAUTH_URL=${NEXTAUTH_URL})"

# ── Install dependencies ──────────────────────────────────────────────────────
echo "Installing dependencies..."
npm install

echo ""
echo "✓ Setup complete. Run: npm run dev"
